; TurboQuant CUDA server — global defaults
[*]
jinja = true
flash-attn = auto
ngl = 99
parallel = 2
ctx-size = 16384

[nemotron-3-nano-4b]
model = C:\Users\wubwu\.ollama\models\blobs\sha256-527db2cf6c705d8fabb95693d038d9c06b4a2b0b8b0a4bbdbd01212d37242970
alias = nemotron-3-nano:4b

[deepseek-coder-v2-16b]
model = C:\Users\wubwu\.ollama\models\blobs\sha256-5ff0abeeac1d2dbdd5455c0b49ba3b29a9ce3c1fb181b2eef2e948689d55d046
alias = deepseek-coder-v2:16b

[lfm2-24b-q4_K_M]
parallel = 1
ctx-size = 32768
model = C:\Users\wubwu\.ollama\models\blobs\sha256-d55ab0bfb1b80102465eef8a17f05d201fb17dbe27a62f153f0db6c446aed077
alias = lfm2:24b-q4_K_M

[ibm-granite4-7b-a1b-h]
model = C:\Users\wubwu\.ollama\models\blobs\sha256-491ba81786c46a345a5da9a60cdb9f9a3056960c8411dd857153c194b1f91313
alias = ibm/granite4:7b-a1b-h

[qwen3.5-35b-a3b-q4_K_M]
parallel = 1
ctx-size = 65536
model = C:\Users\wubwu\models\gguf\Qwen_Qwen3.5-35B-A3B-Q4_K_M.gguf
alias = qwen3.5:35b-a3b-q4_K_M, qwen3.5:35b-a3b, qwen3.5:35b
